[package]
name = "thread-tracker"
version = "0.2.2"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-runtime = "0.15.0"
anyhow = "1.0.70"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "cache", "temp_cache"] }
shuttle-secrets = "0.15.0"
shuttle-serenity = "0.15.0"
tokio = "1.27.0"
tracing = "0.1.37"
serde = "1.0.159"
shuttle-shared-db = { version = "0.15.0", features = ["postgres"] }
sqlx = { version = "0.6.3", features = ["runtime-tokio-native-tls", "postgres"] }
postgres = "0.19.5"
chrono = "0.4.24"
thiserror = "1.0.40"
rand = "0.8.5"
url = "2.3.1"
